// Objective-C API for talking to github.com/katafract-io/hysteria-bind Go package.
//   gobind -lang=objc -prefix="Hys" github.com/katafract-io/hysteria-bind
//
// File is generated by gobind. Do not edit.

#ifndef __HysHysbind_H__
#define __HysHysbind_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class HysHysbindClient;

/**
 * Client is a single Hysteria 2 connection plus its UDP forwarder.
One per active VPN session. Not safe for concurrent Start/Stop, but
Stats() is safe at any time.
 */
@interface HysHysbindClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewClient returns an idle Client. Must call Start before use.
 */
- (nullable instancetype)init;
/**
 * Connected reports whether Start has been called and Stop has not.
(Does not probe the underlying QUIC session — use TxBytes/RxBytes
deltas to spot a dead pipe.)
 */
- (BOOL)connected;
/**
 * RxBytes returns total bytes received from the server.
 */
- (int64_t)rxBytes;
/**
 * Start opens a Hysteria 2 connection to (serverHost:serverPort) using
auth as the Sigil bearer token, listens locally on 127.0.0.1 on a
random port, and tunnels every UDP datagram received there to
wgRemote (the real WireGuard endpoint, e.g. "5.78.207.199:51820").

Returns the local listen address ("127.0.0.1:NNNNN"). The iOS side
configures WireGuardKit to use that as its peer endpoint.
 */
- (NSString* _Nonnull)start:(NSString* _Nullable)serverHost serverPort:(long)serverPort auth:(NSString* _Nullable)auth sni:(NSString* _Nullable)sni insecureSkipVerify:(BOOL)insecureSkipVerify wgRemote:(NSString* _Nullable)wgRemote error:(NSError* _Nullable* _Nullable)error;
/**
 * Stop tears down the local listener and closes the Hysteria connection.
Idempotent.
 */
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
/**
 * TxBytes returns total bytes the iOS side has sent through the tunnel
since Start. Cleared on Stop.
 */
- (int64_t)txBytes;
@end

/**
 * NewClient returns an idle Client. Must call Start before use.
 */
FOUNDATION_EXPORT HysHysbindClient* _Nullable HysHysbindNewClient(void);

#endif
