
// Objective-C API for talking to the following Go packages
//
//	github.com/katafract-io/hysteria-bind
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Hysteria_FRAMEWORK_H__
#define __Hysteria_FRAMEWORK_H__

#include "HysHysbind.objc.h"
#include "Universe.objc.h"

#endif
